# Generated by Django 4.2.4 on 2023-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone', models.CharField(max_length=255)),
                ('phone2', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('lenkidi', models.URLField()),
                ('instaqram', models.URLField()),
                ('twitter', models.URLField()),
                ('bgimage', models.ImageField(upload_to='')),
                ('title', models.CharField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
