# Generated by Django 4.2.4 on 2023-08-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
    ]
